services:
  mysql:
    image: mysql:8.4.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: commerce_example
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: secret
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
