
spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp:localhost/~/h2/db/batch-practice
      username: sa
      password:
      driver-class-name: org.h2.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibenate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.H2Dialect

  batch:
    jdbc:
      initialize-schema: never
      isolation-level-for-create: default
    job:
      #      names: NONE
      #      names: "fileJob"
      enabled: false

#logging.level:
#  org.hibernate.SQL: DEBUG
#  org.hibernate.type: trace

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=utf8
      username: root
      password: pass
      driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: never
