spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: always
      schema-locations: classpath:payment-schema.sql

  thymeleaf:
    cache: false

psp:
  toss:
    url: https://api.tosspayments.com
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

logging:
  level:
    org.apache.coyote.http11: trace
    org.hibernate:
      sql: debug
      orm.jdbc.bind: trace

