spring:

  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment
    username: root
    password:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

psp:
  toss:
    url: https://api.tosspayments.com
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
