// "use client"; // Client Component 로 사용
import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";

/**
 * content 바깥의 공통된 내용은 layout.js에 작성합니다.
 */

/**
 * Server Component 에서 사용되는 것
 */
export const metadata = {
  title: "Web tutorial",
  description: "Generated by Young rae",
};

export default async function RootLayout({ children }) {
  // next.js 는 fetch 를 사용하면 기본적으로 가져온 데이터를 캐싱합니다.
  // const resp = await fetch("http://localhost:9999/topics");
  // 캐시를 쓰지 않겠음
  // const resp = await fetch("http://localhost:9999/topics", {next: { revalidate: 0 }});
  const resp = await fetch(process.env.API_URL + "/topics", {cache: "no-cache"});
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={"/read/" + topic.id}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
