spring:
  profiles:
    active: local, naver-client

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:lsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create # TODO 추후 옵션 변경
    properties:
      hibernate:
        format_sql: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 100
        minimum-number-of-calls: 10
        wait-duration-in-open-state:
          seconds: 20
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 10