server.port: 9001

spring:
  application:
    name: kukeboard-article-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comment
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none

logging.level:
  org.hibernate:
    SQL: debug
    orm.jdbc.bind: trace