

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: hello-actuator
    company: yr
server:
  tomcat:
    mbeanregistry:
      enabled: true