spring:
  h2:
    console:
      enabled: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:hodolog
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging.level:
  org.hibernate:
    SQL: DEBUG
    type: trace