spring:
  mvc:
    static-path-pattern: /static/**
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_CLIENT_ID_GOOGLE}
            client-secret: ${OAUTH2_CLIENT_SECRET_GOOGLE}
            scope: openid,profile,email
          naver:
            client-id: ${OAUTH2_CLIENT_ID_NAVER}
            client-secret: ${OAUTH2_CLIENT_SECRET_NAVER}
            authorization-grant-type: authorization_code
            client-name: naver-oauth2-practice
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope: profile,email
          kakao:
            client-id: ${OAUTH2_CLIENT_ID_KAKAO}
            client-secret: ${OAUTH2_CLIENT_SECRET_KAKAO}
            client-name: oauth2-practice
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
#            scope: openid,profile_nickname,profile_image,account_email
            scope: profile_nickname,profile_image,account_email
          keycloak:
            authorization-grant-type: authorization_code
            client-name: oauth2-client-app
            client-id: ${OAUTH2_CLIENT_ID_KEYCLOAK}
            client-secret: ${OAUTH2_CLIENT_SECRET_KEYCLOAK}
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            client-authentication-method: client_secret_post
            scope: openid,email,profile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            jwk-set-uri: https://openapi.naver.com/v1/nid/verify
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            # OpenID Connect ? ?? jwkSet URI ? ???? ?? ??? ????
            issuer-uri: https://kauth.kakao.com
            # issur-uri ? ???? ?? ??? ??? ? ??
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me

#            user-name-attribute: id # OpenID Connect ? ????? ???? ?? ??
            user-name-attribute: sub
            # OpenID Connect ? ?? nameAttributeKey ? sub ?? ??? ??? ??? ???? ??
          keycloak:
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            issuer-uri: http://localhost:8080/realms/oauth2
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

server:
  port: 8081

logging:
  level:
    org.springframework.security: debug

